### ISSUE TITLE
Flickering tooltip

### ISSUE THREAD

**Issue by DarkPiep** [GitWither/Unreal-Space-Program#9]
**What happens:**

Hovering over the planet select shows a flickering tooltip

**What I expected to happen:**

It doesn't flicker

**Steps to reproduce:**
1. Hover over the planet select

**Comment by GitWither** [comment]
Seems to be happening on some resolutions

**Comment by GitWither** [comment]
Comes from this line:
https://github.com/GitWither/Unreal-Space-Program/blob/1a540ebe6ca65f6194794b39771ac084205dbb33/Assets/Scripts/mainScript.cs#L108

**Comment by GitWither** [comment]
Currently fixed with this line:
https://github.com/GitWither/Unreal-Space-Program/blob/235e04289b52b1bbcf0099921910901ada3f0ab5/Assets/Scripts/mainScript.cs#L107

This bug might return in the future
